[project]
name = "dbt-core"
version = "1.8.4-touchmarine"

[tool.mypy]
# TODO: widen range of files as we fix issues
files = 'core/dbt'
mypy_path = "third-party-stubs/"
namespace_packages = true

[tool.black]
line-length = 99
target-version = ['py38']

[tool.setuptools]
packages = ["core"]
